#!/usr/bin/env julia
#
# PROVENANCE.md — records the experiments-repo commit and outputs/environment.txt (Julia/package
# versions, hardware) alongside the exported CSVs, so a stale data/ directory is easy to spot.
#
# Usage: julia --project=. analysis/paper/provenance.jl [outdir]

isdefined(Main, :write_csv) || include(joinpath(@__DIR__, "common.jl"))

function export_provenance()
    envfile = joinpath(REPO_ROOT, "outputs", "environment.txt")
    content = isfile(envfile) ? read(envfile, String) : "(no outputs/environment.txt found)"
    commit = try strip(read(`git -C $REPO_ROOT rev-parse HEAD`, String)) catch; "unknown" end
    open(joinpath(OUTDIR, "PROVENANCE.md"), "w") do io
        println(io, "# Provenance")
        println(io, "\nGenerated by `analysis/paper/`.")
        println(io, "\nexperiments repo commit: `$commit`")
        println(io, "\n## outputs/environment.txt\n\n```\n$content\n```")
    end
    println("  wrote $(joinpath(OUTDIR, "PROVENANCE.md"))")
end

abspath(PROGRAM_FILE) == (@__FILE__) && export_provenance()
