# RTS-GMLC large-scale case study (5-minute, 105k steps; selective grid).
inputs = ["gridmod/rts"]

master_seed = 382507
n_seeds     = 10

solver      = "gurobi"
inputs_dir  = "../inputs"
outputs_dir = "../outputs"
